# This is a basic workflow to help you get started with Actions

name: Test compilation

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: install compilers
        run: |
          sudo apt install gcc-10 g++-10
          export CC=/usr/bin/gcc-10
          export CXX=/usr/bin/g++-10
      - name: Setup directories
        run: |
          echo "HOME="
          echo $HOME
          echo "CC="
          echo $gcc
          echo "CXX="
          echo $g++
          mkdir $HOME/pressio_repos 
          export PRESSIO_REPOS=$HOME/pressio_repos
          export PRESSIO_BUILDS=$HOME/pressio_builds

      # - name: Clone Repos 
      #   run: |
      #     cd ${PRESSIO_REPOS}

      #     git clone https://github.com/Pressio/pressio.git
      #     git clone https://github.com/Pressio/pressio-builder.git
      #     git clone https://github.com/Pressio/pressio4py.git

          
#       # Runs a single command using the runners shell
#       - name: Running doxygen
#         run: |
#           pwd
#           cd docs/
#           doxygen Doxyfile
          
#       # Runs a single command using the runners shell
#       - name: Generate html
#         run: |
#           cd ..
#           git clone https://github.com/mosra/m.css.git
#           cd m.css/documentation
#           pwd
#           ls -lh ../../pressio/docs/
#           ./doxygen.py ../../pressio/docs/conf.py
          
#       - name: Commit changes
#         run: |
#           pwd
#           cd docs/
#           touch temp_file.txt
#           git config --local user.email "action@github.com"
#           git config --local user.name "GitHub Action"
#           git add html
#           git add html/*.*
#           git add xml
#           git add xml/*.*
#           git commit -m "Generated html and xml via github action" -a
          
          
#       - name: Push changes
#         uses: ad-m/github-push-action@master
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
                    
#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           pwd
#           echo Add other actions to build,
#           echo test, and deploy your project.
