# This is a basic workflow to help you get started with Actions

name: Test compilation

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
        cxx-compilers: [g++-10]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
      
    - name: Clone Repos
      run: |
        pwd
        ls -lh
        git submodule update --init
        cd pressio/
        git checkout develop
        git branch
        ls -lh

    - name: Build
      env:
        CXX:  ${{matrix.cxx-compilers}}
      run: |
        echo "Compilers:"
        echo $CXX
        python setup.py build

    - name: Unit tests
      run: |
        pip install pytest numpy
        cd build/lib*
        python -m pytest

    - name: install
      env:
        CXX:  ${{matrix.cxx-compilers}}
      run: |
        python setup.py install

    - name: Regression tests
      run: |
        pip install pytest
        pytest
